VAL_PRO_BKP

VAL_PRO_ESDRAS_LOG

DELETE VAL_PRO_BKP
WHERE CD_TAB_FAT = 9
AND VL_HONORARIO = 150
AND CD_PRO_FAT = 41001044;

SELECT * FROM VAL_PRO_BKP WHERE CD_TAB_FAT = 9
                AND VL_HONORARIO = 150
                AND CD_PRO_FAT = 41001044;