CREATE TABLE PACI_CUBO2_ESDRAS AS
SELECT *
FROM PACIENTE
WHERE ROWNUM <= 1000


SELECT * FROM PACI_CUBO2_ESDRAS

-- EXERCICIO 1
DELETE FROM PACI_CUBO2_ESDRAS WHERE TP_SEXO = 'M'

-- EXERCICIO 2
INSERT INTO PACI_CUBO2_ESDRAS
SELECT * FROM PACIENTE WHERE PACIENTE.NM_PACIENTE LIKE 'X%'

-- EXERCCICIO 3
UPDATE PACI_CUBO2_ESDRAS SET TP_SITUACAO = 'S'
WHERE NM_PACIENTE LIKE 'W%'

