--<DS_SCRIPT>
-- DESCRIÇÃO...: SCRIPT CURSO CUBOS 2
-- RESPONSAVEL.: ESDRAS GOMES SANTIAGO
-- DATA........: 14/10/2021
-- APLICAÇÃO...: FFCV - FATURAMENTO DE CONVENIOS
--</DS_SCRIPT>


CREATE TABLE DBAMV.ITTURMA_CUBOS2_EG (

	CD_ITCUBOS		 NUMBER(5,0) 	NOT NULL,
	CD_CUBOS		 NUMBER(5,0) 	NOT NULL,
	DS_CUBOS		 VARCHAR2(200) 	NOT NULL,
	DT_CUBOS		 DATE			NOT NULL,
	CD_MULTI_EMPRESA NUMBER(5,0) 	NOT NULL

)
	TABLESPACE mv2000_d
/

CREATE INDEX DBAMV.IND_ITTURMA_CUBOS2_EG_FK
  ON DBAMV.ITTURMA_CUBOS2_EG (
    cd_multi_empresa
  )
  TABLESPACE mv2000_i
  compute statistics
/

ALTER TABLE DBAMV.ITTURMA_CUBOS2_EG
	ADD CONSTRAINT CNT_CD_ITCUBOS_PK PRIMARY KEY (
      CD_ITCUBOS
 )
	USING INDEX
	  TABLESPACE mv2000_i
	  COMPUTE STATISTICS
/

ALTER TABLE DBAMV.ITTURMA_CUBOS2_EG
  ADD CONSTRAINT CNT_ITTURMA_CUBOS2_EG_1_FK FOREIGN KEY (
    cd_multi_empresa
  ) REFERENCES DBAMV.multi_empresas (
    cd_multi_empresa
  )
/

ALTER TABLE DBAMV.ITTURMA_CUBOS2_EG
  ADD CONSTRAINT CNT_ITTURMA_CUBOS2_EG_2_FK FOREIGN KEY (
    CD_CUBOS
  ) REFERENCES DBAMV.TURMA_CUBOS2_EG (
    CD_CUBOS
  )
/

CREATE SEQUENCE DBAMV.SEQ_ITTURMA_CUBOS2_EG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
GRANT SELECT ON DBAMV.SEQ_ITTURMA_CUBOS2_EG TO DBAPS
/
GRANT SELECT ON DBAMV.SEQ_ITTURMA_CUBOS2_EG TO DBASGU
/
GRANT SELECT ON DBAMV.SEQ_ITTURMA_CUBOS2_EG TO MV2000
/
GRANT SELECT ON DBAMV.SEQ_ITTURMA_CUBOS2_EG TO MVINTEGRA
/
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ITTURMA_CUBOS2_EG FOR DBAMV.SEQ_ITTURMA_CUBOS2_EG
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.ITTURMA_CUBOS2_EG TO DBAPS
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.ITTURMA_CUBOS2_EG TO DBASGU
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.ITTURMA_CUBOS2_EG TO MV2000
/
GRANT DELETE,INSERT,SELECT,UPDATE ON DBAMV.ITTURMA_CUBOS2_EG TO MVINTEGRA
/
COMMENT ON TABLE DBAMV.ITTURMA_CUBOS2_EG IS 'TABELA RESPONSAVEL DO TREINAMENTO DO CUBOS 2'
/
COMMENT ON COLUMN DBAMV.ITTURMA_CUBOS2_EG.CD_CUBOS IS 'CÓDIGO GERADO POR SEQUENCE'
/
COMMENT ON COLUMN DBAMV.ITTURMA_CUBOS2_EG.DS_CUBOS IS 'DESCRIÇÃO DA TABELA DA TURMA CUBOS'
/
COMMENT ON COLUMN DBAMV.ITTURMA_CUBOS2_EG.DT_CUBOS IS 'DATA DE GERAÇÃO DO REGISTRO'
/
COMMENT ON COLUMN DBAMV.ITTURMA_CUBOS2_EG.CD_MULTI_EMPRESA IS 'LOV DE MULTI_EMPRESA'
/


