--<DS_SCRIPT>
-- DESCRIÇÃO...: SCRIPT DE CRIAÇÃO DA TABELA DE AVALIAÇÃO DO CUBO 2
-- RESPONSAVEL.: ESDRAS GOMES SANTIAGO
-- DATA........: 18/10/2021
-- APLICAÇÃO...: FFCV - FATURAMENTO DE CONVENIOS
--</DS_SCRIPT>

CREATE TABLE DBAMV.CUBOS2_AVALIACAO_EGS (                                   

    CD_AVALIACAO          NUMBER(5,0)     NOT NULL,
    CD_MULTI_EMPRESA      NUMBER(4,0)     NOT NULL,
    DS_EMPRESA            VARCHAR2(100)   NOT NULL,
    CD_CONVENIO           NUMBER(3,0)     NOT NULL,
    NM_CONVENIO           VARCHAR2(60)    NOT NULL,
    CD_PLANO              VARCHAR2(10)   NULL,
    DS_PLANO              VARCHAR2(100)   NULL,
    CD_ORIGEM             NUMBER(12,0)     NOT NULL,
    DS_ORIGEM             VARCHAR2(100)   NULL,
    SN_ATIVO              VARCHAR2(1)     DEFAULT 'S' NOT NULL

)
    TABLESPACE mv2000_d
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
    ADD CONSTRAINT CNT_CD_AVALIACAO_EGS_PK PRIMARY KEY (
        CD_AVALIACAO
    )
    USING INDEX 
        TABLESPACE mv2000_i
        COMPUTE STATISTICS
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
    ADD CONSTRAINT CNT_SN_ATIVO_EGS_1_CK CHECK(
        SN_ATIVO IN ('S','N')
    )
/

PROMPT CREATE INDEX dbamv.CUBOS2_AVALIACAO_EGS_fk_i
CREATE INDEX dbamv.CUBOS2_AVALIACAO_EGS_fk_i
  ON dbamv.CUBOS2_AVALIACAO_EGS (
    cd_multi_empresa,
    cd_convenio,
    cd_plano,
    cd_ori_ate
  )
  TABLESPACE mv2000_i
  compute statistics
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
  ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_1_FK FOREIGN KEY (
    CD_MULTI_EMPRESA
  ) REFERENCES DBAMV.multi_empresas (
    cd_multi_empresa
  )
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
  ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_2_FK FOREIGN KEY (
    CD_CONVENIO
  ) REFERENCES DBAMV.CONVENIO (
    cd_convenio
  )
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
  ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_3_FK FOREIGN KEY (
    CD_PLANO
  ) REFERENCES DBAMV.plano (
    cd_plano
  )
/

ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
  ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_4_FK FOREIGN KEY (
    cd_origem
  ) REFERENCES DBAMV.ori_ate (
    cd_ori_ate
  )
/

CREATE SEQUENCE DBAMV.SEQ_CUBOS2_AVALIACAO_EGS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBAPS
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBASGU
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MV2000
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MVINTEGRA
/
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CUBOS2_AVALIACAO_EGS FOR DBAMV.SEQ_CUBOS2_AVALIACAO_EGS
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.CUBOS2_AVALIACAO_EGS TO DBAPS
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.CUBOS2_AVALIACAO_EGS TO DBASGU
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.CUBOS2_AVALIACAO_EGS TO MV2000
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.CUBOS2_AVALIACAO_EGS TO MVINTEGRA
/
COMMENT ON TABLE DBAMV.CUBOS2_AVALIACAO_EGS IS 'TABELA RESPONSÁVEL DA AVALIAÇÃO DO CUBOS 2'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.CD_AVALIACAO IS 'CÓDIGO GERADO POR SEQUENCE'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.CD_MULTI_EMPRESA IS 'CÓDIGO DA EMPRESA'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.DS_EMPRESA IS 'DESCRIÇÃO DA EMPRESA'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.CD_CONVENIO IS 'CÓDIGO DO CONVÊNIO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.NM_CONVENIO IS 'DESCRIÇÃO DO CONVÊNIO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.CD_PLANO IS 'CÓDIGO DO PLANO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.DS_PLANO IS 'DESCRIÇÃO DO PLANO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.CD_ORIGEM IS 'CÓDIGO DA ORIGEM'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.DS_ORIGEM IS 'DESCRIÇÃO DA ORIGEM'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.SN_ATIVO IS 'CAMPO SE É ATIVO OU NÃO'
/