--<DS_SCRIPT>
-- DESCRIÇÃO...: SCRIPT CURSO CUBOS 2
-- RESPONSAVEL.: ESDRAS GOMES SANTIAGO
-- DATA........: 11/10/2021
-- APLICAÇÃO...: FFCV - FATURAMENTO DE CONVENIOS
--</DS_SCRIPT>


CREATE TABLE DBAMV.TURMA_CUBOS2_EG (

    CD_CUBOS    NUMBER(5,0)     NOT NULL,
    DS_CUBOS    VARCHAR2(200)   NOT NULL,
    DT_CUBOS    DATE            NOT NULL,
    TP_CUBOS    VARCHAR2(1)     DEFAULT 'A'    NOT NULL

)
    TABLESPACE mv2000_d
/

ALTER TABLE DBAMV.TURMA_CUBOS2_EG
    ADD CONSTRAINT CNT_CD_CUBOS_EG_PK PRIMARY KEY (
        CD_CUBOS
    )
    USING INDEX 
        TABLESPACE mv2000_i
        COMPUTE STATISTICS
/

ALTER TABLE DBAMV.TURMA_CUBOS2_EG
    ADD CONSTRAINT CNT_TP_CUBOS_EG_1_CK CHECK(
        TP_CUBOS IN ('A','P')
    )
/

CREATE SEQUENCE DBAMV.SEQ_TURMA_CUBOS2_EG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
GRANT SELECT ON DBAMV.SEQ_TURMA_CUBOS2_EG TO DBAPS
/
GRANT SELECT ON DBAMV.SEQ_TURMA_CUBOS2_EG TO DBASGU
/
GRANT SELECT ON DBAMV.SEQ_TURMA_CUBOS2_EG TO MV2000
/
GRANT SELECT ON DBAMV.SEQ_TURMA_CUBOS2_EG TO MVINTEGRA
/
CREATE OR REPLACE PUBLIC SYNONYM SEQ_TURMA_CUBOS2_EG FOR DBAMV.SEQ_TURMA_CUBOS2_EG
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.TURMA_CUBOS2_EG TO DBAPS
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.TURMA_CUBOS2_EG TO DBASGU
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.TURMA_CUBOS2_EG TO MV2000
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.TURMA_CUBOS2_EG TO MVINTEGRA
/
COMMENT ON TABLE DBAMV.TURMA_CUBOS2_EG IS 'TABELA RESPONSÁVEL DO TREINAMENTO DO CUBOS 2'
/
COMMENT ON COLUMN DBAMV.TURMA_CUBOS2_EG.CD_CUBOS IS 'CÓDIGO GERADO POR SEQUENCE'
/
COMMENT ON COLUMN DBAMV.TURMA_CUBOS2_EG.DS_CUBOS IS 'DESCRIÇÃO DA TABELA DA TURMA CUBOS'
/
COMMENT ON COLUMN DBAMV.TURMA_CUBOS2_EG.DT_CUBOS IS 'DATA DA GERAÇÃO DO REGISTRO'
/
COMMENT ON COLUMN DBAMV.TURMA_CUBOS2_EG.TP_CUBOS IS 'TIPO SE É ALUNO OU PROFESSOR'
/