--<DS_SCRIPT>
-- DESCRIÇÃO...: SCRIPT DA AVALIAÇÃO DO CURSO CUBOS 2
-- RESPONSAVEL.: ESDRAS GOMES
-- DATA........: 18/10/2021
-- APLICAÇÃO...: FFCV - FATURAMENTO DE CONVENIOS
--</DS_SCRIPT>




CREATE TABLE DBAMV.CUBOS2_AVALIACAO_EGS (



cd_avaliacao NUMBER(5,0) NOT NULL,
cd_multi_empresa NUMBER(4,0) NOT NULL,
ds_multi_empresa VARCHAR2(200),
cd_convenio NUMBER(3,0) NOT NULL,
nm_convenio VARCHAR2(60),
cd_plano NUMBER(4,0) NOT NULL,
ds_plano VARCHAR2(30) NOT NULL,
cd_ori_ate NUMBER(12,0) NOT NULL,
ds_ori_ate VARCHAR2(200),
sn_ativo VARCHAR2(1) DEFAULT 'S' NOT NULL



)
TABLESPACE mv2000_d
/



PROMPT CREATE INDEX dbamv.CUBOS2_AVALIACAO_EGS_fk_i
CREATE INDEX dbamv.CUBOS2_AVALIACAO_EGS_fk_i
ON dbamv.CUBOS2_AVALIACAO_EGS (
cd_multi_empresa,
cd_convenio,
cd_plano,
cd_ori_ate
)
TABLESPACE mv2000_i
compute statistics
/




ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_CD_AVALIACAO_EGS_PK PRIMARY KEY (
CD_AVALIACAO
)
USING INDEX
TABLESPACE mv2000_i
COMPUTE STATISTICS
/



ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_1_FK FOREIGN KEY (
cd_multi_empresa
) REFERENCES DBAMV.multi_empresas (
cd_multi_empresa
)
/



ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_2_FK FOREIGN KEY (
cd_convenio
) REFERENCES DBAMV.convenio (
cd_convenio
)
/



ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_3_FK FOREIGN KEY (
cd_plano,
cd_convenio
) REFERENCES DBAMV.con_pla (
cd_con_pla,
cd_convenio
)
/



ALTER TABLE DBAMV.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_CUBOS2_AVALIACAO_EGS_4_FK FOREIGN KEY (
cd_ori_ate
) REFERENCES DBAMV.ori_ate (
cd_ori_ate
)
/




ALTER TABLE dbamv.CUBOS2_AVALIACAO_EGS
ADD CONSTRAINT CNT_SN_ATIVO_EGS_1_CK CHECK (
SN_ATIVO IN ('S', 'N')
)
/



CREATE SEQUENCE DBAMV.SEQ_CUBOS2_AVALIACAO_EGS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBAPS
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBASGU
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MV2000
/
GRANT SELECT ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MVINTEGRA
/
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CUBOS2_AVALIACAO_EGS FOR DBAMV.SEQ_CUBOS2_AVALIACAO_EGS
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBAPS
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO DBASGU
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MV2000
/
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMV.SEQ_CUBOS2_AVALIACAO_EGS TO MVINTEGRA
/
COMMENT ON TABLE DBAMV.CUBOS2_AVALIACAO_EGS IS 'TABELA RESPONSÁVEL DO TREINAMENTO DO CUBOS 2'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.cd_avaliacao IS 'CÓDIGO GERADO POR SEQUENCE'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.cd_multi_empresa IS 'CÓDIGO DA EMPRESA'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.ds_multi_empresa IS 'DESCRIÇÃO DA EMPRESA'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.cd_convenio IS 'CÓDIGO DO CONVENIO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.nm_convenio IS 'DESCRIÇÃO CONVENIO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.cd_plano IS 'CÓDIGO DO PLANO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.ds_plano IS 'DESCRIÇÃO DO PLANO'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.cd_ori_ate IS 'CÓDIGO DA ORIGEM'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.ds_ori_ate IS 'DESCRIÇÃO DA ORIGEM'
/
COMMENT ON COLUMN DBAMV.CUBOS2_AVALIACAO_EGS.sn_ativo IS 'TIPO SE ESTÁ ATIVO OU NÃO'
/