CREATE OR REPLACE FUNCTION FNC_IDADE_ESDRAS

  ( I_PACIENTE IN NUMBER ) RETURN NUMBER IS

  CURSOR IDADE IS SELECT Trunc((SYSDATE - DT_NASCIMENTO) / 365)
                  FROM PACIENTE
                  WHERE CD_PACIENTE = I_PACIENTE;

  vRetornaIdade number(10);

BEGIN

  OPEN IDADE;
  FETCH IDADE INTO vRetornaIdade;
  CLOSE IDADE;

  RETURN vRetornaIdade;

END;
/

-- SELECT PARA VER SE A FUNÇÃO FOI CRIADA E ESTÁ FUNCIONANDO COMO O ESPERADO
SELECT FNC_IDADE_ESDRAS(9) FROM DUAL